// petstore-base API for pets
// Generated by @f3liz/rescript-autogen-openapi
// DO NOT EDIT - This file is auto-generated



type getpetsResponse = array<PetstoreBaseComponentSchemas.Pet.t>

let getpetsResponseSchema = S.array(PetstoreBaseComponentSchemas.Pet.schema)

/** List all pets */
let getpets = (~body as _, ~fetch: (~url: string, ~method_: string, ~body: option<JSON.t>) => Promise.t<JSON.t>): promise<getpetsResponse> => {

  fetch(
    ~url="/pets",
    ~method_="GET",
    ~body=None,
  )->Promise.then(response => {
  let value = response->S.parseOrThrow(getpetsResponseSchema)
  value
    ->Promise.resolve
  })
}

type postpetsRequest = PetstoreBaseComponentSchemas.Pet.t

let postpetsRequestSchema = PetstoreBaseComponentSchemas.Pet.schema

type postpetsResponse = unit

/** Create a pet */
let postpets = (~body: postpetsRequest, ~fetch: (~url: string, ~method_: string, ~body: option<JSON.t>) => Promise.t<JSON.t>): promise<postpetsResponse> => {
  let jsonBody = body->S.reverseConvertToJsonOrThrow(postpetsRequestSchema)
  fetch(
    ~url="/pets",
    ~method_="POST",
    ~body=Some(jsonBody),
  )->Promise.then(response => {
  let _ = response
  ()
    ->Promise.resolve
  })
}

type getpetsResponse = PetstoreBaseComponentSchemas.Pet.t

let getpetsResponseSchema = PetstoreBaseComponentSchemas.Pet.schema

/** Info for a specific pet */
let getpets = (~body as _, ~fetch: (~url: string, ~method_: string, ~body: option<JSON.t>) => Promise.t<JSON.t>): promise<getpetsResponse> => {

  fetch(
    ~url="/pets/{petId}",
    ~method_="GET",
    ~body=None,
  )->Promise.then(response => {
  let value = response->S.parseOrThrow(getpetsResponseSchema)
  value
    ->Promise.resolve
  })
}
