// Shared component schemas
// Generated by @f3liz/rescript-autogen-openapi
// DO NOT EDIT - This file is auto-generated

S.enableJson()


module Pet = {
  type t = {
  id: int,
  name: string,
  tag: option<string>,
}
  let schema = S.object(s => {
    id: s.field("id", S.int),
    name: s.field("name", S.string),
    tag: s.field("tag", S.option(S.string)),
  })
}