// cherrypick API for clips
// Generated by rescript-codegen-openapi
// DO NOT EDIT - This file is auto-generated



type postClipsCreateRequest = {
  name: string,
  isPublic: option<bool>,
  description: option<JSON.t>,
}

let postClipsCreateRequestSchema = S.object(s => {
    name: s.field("name", S.string->S.min(1)->S.max(100)),
    isPublic: s.fieldOr("isPublic", S.nullableAsOption(S.bool), None),
    description: s.fieldOr("description", S.nullableAsOption(S.json), None),
  })

type postClipsCreateResponse = CherrypickComponentSchemas.Clip.t

let postClipsCreateResponseSchema = CherrypickComponentSchemas.Clip.schema

/**
 * clips/create
 *
 * No description provided.
 *
 * **Credential required**: *Yes* / **Permission**: *write:account*
 */
let postClipsCreate = (~body: postClipsCreateRequest, ~fetch: (~url: string, ~method_: string, ~body: option<JSON.t>) => Promise.t<JSON.t>): promise<postClipsCreateResponse> => {
  let jsonBody = body->S.reverseConvertToJsonOrThrow(postClipsCreateRequestSchema)
  fetch(
    ~url="/clips/create",
    ~method_="POST",
    ~body=Some(jsonBody),
  )->Promise.then(response => {
  let value = response->S.parseOrThrow(postClipsCreateResponseSchema)
  value
    ->Promise.resolve
  })
}

type postClipsListRequest = {
  limit: option<int>,
  sinceId: option<string>,
  untilId: option<string>,
  sinceDate: option<int>,
  untilDate: option<int>,
}

let postClipsListRequestSchema = S.object(s => {
    limit: s.fieldOr("limit", S.nullableAsOption(S.int->S.min(1)->S.max(100)), None),
    sinceId: s.fieldOr("sinceId", S.nullableAsOption(S.string), None),
    untilId: s.fieldOr("untilId", S.nullableAsOption(S.string), None),
    sinceDate: s.fieldOr("sinceDate", S.nullableAsOption(S.int), None),
    untilDate: s.fieldOr("untilDate", S.nullableAsOption(S.int), None),
  })

type postClipsListResponse = array<CherrypickComponentSchemas.Clip.t>

let postClipsListResponseSchema = S.array(CherrypickComponentSchemas.Clip.schema)

/**
 * clips/list
 *
 * No description provided.
 *
 * **Credential required**: *Yes* / **Permission**: *read:account*
 */
let postClipsList = (~body: postClipsListRequest, ~fetch: (~url: string, ~method_: string, ~body: option<JSON.t>) => Promise.t<JSON.t>): promise<postClipsListResponse> => {
  let jsonBody = body->S.reverseConvertToJsonOrThrow(postClipsListRequestSchema)
  fetch(
    ~url="/clips/list",
    ~method_="POST",
    ~body=Some(jsonBody),
  )->Promise.then(response => {
  let value = response->S.parseOrThrow(postClipsListResponseSchema)
  value
    ->Promise.resolve
  })
}

type postClipsShowRequest = {
  clipId: string,
}

let postClipsShowRequestSchema = S.object(s => {
    clipId: s.field("clipId", S.string),
  })

type postClipsShowResponse = CherrypickComponentSchemas.Clip.t

let postClipsShowResponseSchema = CherrypickComponentSchemas.Clip.schema

/**
 * clips/show
 *
 * No description provided.
 *
 * **Credential required**: *No* / **Permission**: *read:account*
 */
let postClipsShow = (~body: postClipsShowRequest, ~fetch: (~url: string, ~method_: string, ~body: option<JSON.t>) => Promise.t<JSON.t>): promise<postClipsShowResponse> => {
  let jsonBody = body->S.reverseConvertToJsonOrThrow(postClipsShowRequestSchema)
  fetch(
    ~url="/clips/show",
    ~method_="POST",
    ~body=Some(jsonBody),
  )->Promise.then(response => {
  let value = response->S.parseOrThrow(postClipsShowResponseSchema)
  value
    ->Promise.resolve
  })
}

type postClipsUpdateRequest = {
  clipId: string,
  name: option<string>,
  isPublic: option<bool>,
  description: option<JSON.t>,
}

let postClipsUpdateRequestSchema = S.object(s => {
    clipId: s.field("clipId", S.string),
    name: s.fieldOr("name", S.nullableAsOption(S.string->S.min(1)->S.max(100)), None),
    isPublic: s.fieldOr("isPublic", S.nullableAsOption(S.bool), None),
    description: s.fieldOr("description", S.nullableAsOption(S.json), None),
  })

type postClipsUpdateResponse = CherrypickComponentSchemas.Clip.t

let postClipsUpdateResponseSchema = CherrypickComponentSchemas.Clip.schema

/**
 * clips/update
 *
 * No description provided.
 *
 * **Credential required**: *Yes* / **Permission**: *write:account*
 */
let postClipsUpdate = (~body: postClipsUpdateRequest, ~fetch: (~url: string, ~method_: string, ~body: option<JSON.t>) => Promise.t<JSON.t>): promise<postClipsUpdateResponse> => {
  let jsonBody = body->S.reverseConvertToJsonOrThrow(postClipsUpdateRequestSchema)
  fetch(
    ~url="/clips/update",
    ~method_="POST",
    ~body=Some(jsonBody),
  )->Promise.then(response => {
  let value = response->S.parseOrThrow(postClipsUpdateResponseSchema)
  value
    ->Promise.resolve
  })
}
