// misskey API for role
// Generated by @f3liz/rescript-autogen-openapi
// DO NOT EDIT - This file is auto-generated



type postRolesListResponse = array<MisskeyComponentSchemas.Role.t>

let postRolesListResponseSchema = S.array(MisskeyComponentSchemas.Role.schema)

/**
 * roles/list
 *
 * No description provided.
 *
 * **Credential required**: *Yes* / **Permission**: *read:account*
 */
let postRolesList = (~body as _, ~fetch: (~url: string, ~method_: string, ~body: option<JSON.t>) => Promise.t<JSON.t>): promise<postRolesListResponse> => {

  fetch(
    ~url="/roles/list",
    ~method_="POST",
    ~body=None,
  )->Promise.then(response => {
  let value = response->S.parseOrThrow(postRolesListResponseSchema)
  value
    ->Promise.resolve
  })
}

type postRolesNotesRequest = {
  roleId: string,
  limit: option<int>,
  sinceId: option<string>,
  untilId: option<string>,
  sinceDate: option<int>,
  untilDate: option<int>,
  dimension: option<JSON.t>,
}

let postRolesNotesRequestSchema = S.object(s => {
    roleId: s.field("roleId", S.string),
    limit: s.fieldOr("limit", S.nullableAsOption(S.int->S.min(1)->S.max(100)), None),
    sinceId: s.fieldOr("sinceId", S.nullableAsOption(S.string), None),
    untilId: s.fieldOr("untilId", S.nullableAsOption(S.string), None),
    sinceDate: s.fieldOr("sinceDate", S.nullableAsOption(S.int), None),
    untilDate: s.fieldOr("untilDate", S.nullableAsOption(S.int), None),
    dimension: s.fieldOr("dimension", S.nullableAsOption(S.json), None),
  })

type postRolesNotesResponse = array<MisskeyComponentSchemas.Note.t>

let postRolesNotesResponseSchema = S.array(MisskeyComponentSchemas.Note.schema)

/**
 * roles/notes
 *
 * No description provided.
 *
 * **Credential required**: *Yes* / **Permission**: *read:account*
 */
let postRolesNotes = (~body: postRolesNotesRequest, ~fetch: (~url: string, ~method_: string, ~body: option<JSON.t>) => Promise.t<JSON.t>): promise<postRolesNotesResponse> => {
  let jsonBody = body->S.reverseConvertToJsonOrThrow(postRolesNotesRequestSchema)
  fetch(
    ~url="/roles/notes",
    ~method_="POST",
    ~body=Some(jsonBody),
  )->Promise.then(response => {
  let value = response->S.parseOrThrow(postRolesNotesResponseSchema)
  value
    ->Promise.resolve
  })
}

type postRolesShowRequest = {
  roleId: string,
}

let postRolesShowRequestSchema = S.object(s => {
    roleId: s.field("roleId", S.string),
  })

type postRolesShowResponse = MisskeyComponentSchemas.Role.t

let postRolesShowResponseSchema = MisskeyComponentSchemas.Role.schema

/**
 * roles/show
 *
 * No description provided.
 *
 * **Credential required**: *No*
 */
let postRolesShow = (~body: postRolesShowRequest, ~fetch: (~url: string, ~method_: string, ~body: option<JSON.t>) => Promise.t<JSON.t>): promise<postRolesShowResponse> => {
  let jsonBody = body->S.reverseConvertToJsonOrThrow(postRolesShowRequestSchema)
  fetch(
    ~url="/roles/show",
    ~method_="POST",
    ~body=Some(jsonBody),
  )->Promise.then(response => {
  let value = response->S.parseOrThrow(postRolesShowResponseSchema)
  value
    ->Promise.resolve
  })
}

type postRolesUsersRequest = {
  roleId: string,
  sinceId: option<string>,
  untilId: option<string>,
  limit: option<int>,
}

let postRolesUsersRequestSchema = S.object(s => {
    roleId: s.field("roleId", S.string),
    sinceId: s.fieldOr("sinceId", S.nullableAsOption(S.string), None),
    untilId: s.fieldOr("untilId", S.nullableAsOption(S.string), None),
    limit: s.fieldOr("limit", S.nullableAsOption(S.int->S.min(1)->S.max(100)), None),
  })

type postRolesUsersResponse = array<{
  id: string,
  user: MisskeyComponentSchemas.UserDetailed.t,
}>

let postRolesUsersResponseSchema = S.array(S.object(s => {
    id: s.field("id", S.string),
    user: s.field("user", MisskeyComponentSchemas.UserDetailed.schema),
  }))

/**
 * roles/users
 *
 * No description provided.
 *
 * **Credential required**: *No*
 */
let postRolesUsers = (~body: postRolesUsersRequest, ~fetch: (~url: string, ~method_: string, ~body: option<JSON.t>) => Promise.t<JSON.t>): promise<postRolesUsersResponse> => {
  let jsonBody = body->S.reverseConvertToJsonOrThrow(postRolesUsersRequestSchema)
  fetch(
    ~url="/roles/users",
    ~method_="POST",
    ~body=Some(jsonBody),
  )->Promise.then(response => {
  let value = response->S.parseOrThrow(postRolesUsersResponseSchema)
  value
    ->Promise.resolve
  })
}
