// Shared component schemas
// Generated by @f3liz/rescript-autogen-openapi
// DO NOT EDIT - This file is auto-generated



module Pet = {
  type t = {
  id: int,
  name: string,
  tag: option<string>,
  age: option<int>,
}
  let schema = S.object(s => {
    id: s.field("id", S.int),
    name: s.field("name", S.string),
    tag: s.fieldOr("tag", S.nullableAsOption(S.string), None),
    age: s.fieldOr("age", S.nullableAsOption(S.int), None),
  })
}