// extended API for store
// Generated by rescript-codegen-openapi
// DO NOT EDIT - This file is auto-generated



type getstoreinventoryResponse = JSON.t

let getstoreinventoryResponseSchema = S.json

/** Returns pet inventories by status */
let getstoreinventory = (~body as _, ~fetch: (~url: string, ~method_: string, ~body: option<JSON.t>) => Promise.t<JSON.t>): promise<getstoreinventoryResponse> => {

  fetch(
    ~url="/store/inventory",
    ~method_="GET",
    ~body=None,
  )->Promise.then(response => {
  let value = response->S.parseOrThrow(getstoreinventoryResponseSchema)
  value
    ->Promise.resolve
  })
}
